name: 'export-and-import-solution'
description: 'Power Platform Export and Import Solution'

# Define the event triggers
on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'

      - name: Install Power Platform CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          dotnet tool list --global

  export:
    needs: setup  # This ensures the export job waits for the setup job to complete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export Solution
        run: |
          pac auth create --clientId ${{ secrets.APP_ID }} --clientSecret ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }} --environment 'https://ard26dev.crm6.dynamics.com'
          pac solution export --name 'ARDDEVNOTE' --outputFile 'solution.zip' --managed false --async false

  import:
    needs: export  # This ensures the import job waits for the export job to complete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Import Solution
        run: |
          pac auth create --clientId ${{ secrets.APP_ID }} --clientSecret ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }} --environment 'https://org7ccdbb6a.crm6.dynamics.com'
          pac solution import --path 'solution.zip' --activate-plugins --overwrite-unmanaged-customizations --skip-dependency-check false
