name: 'export-and-import-solution'
description: 'Power Platform Export and Import Solution'

# Define the event triggers
on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://ard26dev.crm6.dynamics.com/'
          app-id: 'b0ab8343-d672-4e24-86d0-d48c19b67862'
          client-secret: '95859b4c-fd30-46d9-b5dd-8b18bf04a62b'
          tenant-id: 'd1ee9b37-cae3-4945-a777-7b8b03047391'
          solution-name: 'ARDDEVNOTE'
          solution-output-file: 'solution.zip'
          managed: false
          run-asynchronously: false
          cloud: 'Public'
          max-async-wait-time: 60

  import:
    needs: export  # This ensures the import job waits for the export job to complete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Import Solution
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: 'https://org7ccdbb6a.crm6.dynamics.com/'
          app-id: 'b0ab8343-d672-4e24-86d0-d48c19b67862'
          client-secret: '95859b4c-fd30-46d9-b5dd-8b18bf04a62b'
          tenant-id: 'd1ee9b37-cae3-4945-a777-7b8b03047391'
          solution-file: 'solution.zip'
          activate-plugins: true
          overwrite-unmanaged-customizations: true
          skip-dependency-check: false
